
clientId=openelis
clientSecret=3ywNmHiTdhftoIvV79O2mvGTfkA9KvrO

preEstablishedRedirectUri=https://lupinstaging.bahmni.in/openelis/ValidateSSOLogin.do

publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhm3SIVrzGTIROqAHZMq+ZQcAhKkB3haC0w8dZ9l2fT8Xh5TgqHrV8p7BooRLPOaMGN9R+cDjODQSm/sjXl0KUNjaILFrK8WGOnpmBgmnAxLGBNEuGo27/45zlJVXGx4WDvHYSxfMKk9HIbDQU1cSB8FbFDkCyFUyfciybk9hr11WpSBr7j0iZbDSF/SF7KYTJLATbrD370W4AhOH8ey1ctsZwVUD1cmSZC4pto2BMASraVBosxWZFPRTRPjOlxhxBi1boba2820BiPBnNzEp1qC/j7X0TiV/TeLKCtNfDLb8DGbK79IUSy5NonVx1Miy9ZHPG7Cr58HNWCLYZq3fowIDAQAB

userAuthorizationUri=https://kc-dev.bahmni.in/realms/demo/protocol/openid-connect/auth
accessTokenUri=https://kc-dev.bahmni.in/realms/demo/protocol/openid-connect/token
userInfoUri=https://kc-dev.bahmni.in/realms/demo/protocol/openid-connect/userinfo
logoutUri=https://kc-dev.bahmni.in/realms/demo/protocol/openid-connect/logout
keysUrl=https://kc-dev.bahmni.in/realms/demo/protocol/openid-connect/certs

grant-type=authorization_code
scope=openid,profile,email
